### ISSUE TITLE
Recherche commune "Paris" retourne "75116"

### ISSUE THREAD

**Issue by ThomasKientz** [datagouv/api-geo#93]
> https://geo.api.gouv.fr/communes?nom=Paris&fields=nom,codesPostaux,departement&format=json&geometry=centre

Pourquoi retourne-t-elle le code postal "75116" dans les résultats. Il ne semble pas être un véritable code postal mais le code INSEE de 75016 (16eme arrondissement de Paris).

**Comment by jdesboeufs** [comment]
75116 est bien un code postal officiel du 16e arrondissement. Il y en a 2,
c’est une exception.

Le ven. 17 août 2018 à 16:23, Thomas Kientz <notifications@github.com> a
écrit :
